/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:370a1c54-521d-404f-a6e5-c48dd4622b50",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_I2KVbLnjT",
    "aws_user_pools_web_client_id": "7k4adsmrm3mvi6jusb4c3q6pph",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6yd3posyybgali3umr6f7hi4r4.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
